# Default configuration in case none is provided
log_level: debug

python:
  path: /usr/bin/python

java:
  path: /usr/bin/java

open_office:
  path: /Applications/OpenOffice.org.app/Contents/MacOS/soffice #/usr/bin/soffice
  bridge: JOD
  max_cpu: 100
  max_startup_time: 5
  wakeup_time: 3
  max_conversion_attempts: 3
  max_conversion_time: 5