# Default configuration in case none is provided
log_path: ~/documentalist.log

python:
  path: /usr/bin/python

java:
  path: /usr/bin/java

open_office:
  path: /usr/bin/soffice
  bridge: JOD
  max_cpu: 80
  max_startup_time: 3
  wakeup_time: 3
  max_conversion_attempts: 3
  max_conversion_time: 5