development:
  # TODO : Replace me with temp path
  conversions_path: toto
  open_office:
    python_path: /usr/bin/python
    open_office_path: /Applications/OpenOffice.org.app/Contents/MacOS/soffice #/usr/bin/soffice
    bridge: JOD #PYOD
    max_cpu: 80  #percent
    server_start_delay: 10 #seconds
    conversion_tries: 3
    conversion_time_delay: 10 #seconds

test:
  # TODO : Replace me with temp path
  conversions_path: toto
  open_office:
    python_path: /usr/bin/python
    open_office_path: /Applications/OpenOffice.org.app/Contents/MacOS/soffice #/usr/bin/soffice
    bridge: JOD #PYOD
    max_cpu: 80  #percent
    server_start_delay: 10 #seconds
    conversion_tries: 3
    conversion_time_delay: 10 #seconds

production:
  # TODO : Replace me with temp path
  conversions_path: toto
  open_office:
    python_path: /usr/bin/python
    open_office_path: /Applications/OpenOffice.org.app/Contents/MacOS/soffice #/usr/bin/soffice
    bridge: JOD #PYOD
    max_cpu: 80  #percent
    server_start_delay: 10 #seconds
    conversion_tries: 3
    conversion_time_delay: 10 #seconds
